import Head from 'next/head';
import Puzzle from '../components/Puzzle';

const test = [
  [0, 0, 0, 0, 4, 0, 9, 5, 0],
  [0, 8, 0, 0, 9, 0, 0, 0, 7],
  [0, 6, 0, 5, 0, 0, 0, 2, 3],
  [0, 4, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 6, 7, 4, 0, 0, 0],
  [0, 0, 3, 0, 0, 0, 0, 8, 0],
  [4, 3, 0, 0, 0, 1, 0, 7, 0],
  [8, 0, 0, 0, 3, 0, 0, 4, 0],
  [0, 2, 7, 0, 8, 0, 0, 0, 0],
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sudoku Solver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Puzzle puzzle={test} />
      </main>
    </div>
  );
}
