import Head from 'next/head';
import { useState } from 'react';
import Puzzle from '../components/Puzzle';
import {
  getNextEmptyPosition,
  easy2,
  hard,
  solve,
  singleStep,
  doubleStep,
  findTriples,
} from '../utils';

export default function Home() {
  const [puzzle, setPuzzle] = useState(easy2);
  const [position, setPosition] = useState({ x: 0, y: 0 });

  function doTripleStep() {
    console.log(findTriples(puzzle));
  }

  function doDoubleStep() {
    const solution = doubleStep(puzzle);

    if (solution) {
      const temp = JSON.parse(JSON.stringify(puzzle));
      const { x, y, value } = solution;
      temp[y][x] = value;
      setPuzzle(temp);
      setPosition({ x, y });
    }
  }

  function doStep() {
    const solution = singleStep(puzzle, position.x, position.y);
    if (solution) {
      const temp = JSON.parse(JSON.stringify(puzzle));
      temp[position.y][position.x] = solution;
      setPuzzle(temp);
    }
    setPosition(getNextEmptyPosition(puzzle, position));
  }

  return (
    <div>
      <Head>
        <title>Sudoku Solver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Puzzle puzzle={puzzle} highlight={position} />
        <div className="actions">
          <button onClick={doStep}>STEP</button>
          <button onClick={doDoubleStep}>DOUBLE STEP</button>
          <button onClick={doTripleStep}>TRIPLE STEP</button>
          <button onClick={() => setPuzzle(solve(puzzle))}>SOLVE</button>
        </div>
      </main>
    </div>
  );
}
